Repository knative-extensions/eventing-gitlab, pull requests merged in 2020-11, with the labels that each got.

#22 Add antoineco to list of source owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#21 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#23 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#25 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#26 Bump xanzy/go-gitlab and go-playground/webhooks deps
  go.mod
  go.sum
  pkg/adapter/receive_adapter.go
  pkg/adapter/receive_adapter_test.go
  vendor/github.com/xanzy/go-gitlab/.travis.yml
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/client_options.go
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/deploy_keys.go
  vendor/github.com/xanzy/go-gitlab/epics.go
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/freeze_periods.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_boards.go
  vendor/github.com/xanzy/go-gitlab/group_clusters.go
  vendor/github.com/xanzy/go-gitlab/group_labels.go
  vendor/github.com/xanzy/go-gitlab/group_members.go
  vendor/github.com/xanzy/go-gitlab/group_milestones.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/instance_clusters.go
  vendor/github.com/xanzy/go-gitlab/instance_variables.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/issues_statistics.go
  vendor/github.com/xanzy/go-gitlab/jobs.go
  vendor/github.com/xanzy/go-gitlab/labels.go
  vendor/github.com/xanzy/go-gitlab/license.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/milestones.go
  vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/project_members.go
  vendor/github.com/xanzy/go-gitlab/project_mirror.go
  vendor/github.com/xanzy/go-gitlab/project_snippets.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/registry.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/tags.go
  vendor/github.com/xanzy/go-gitlab/types.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/gopkg.in/go-playground/webhooks.v5/gitlab/gitlab.go
  vendor/gopkg.in/go-playground/webhooks.v5/gitlab/payload.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#27 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#28 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#24 Set proper type and source attributes on emitted CloudEvents
  config/300-gitlabsource.yaml
  config/500-controller.yaml
  go.mod
  pkg/adapter/receive_adapter.go
  pkg/adapter/receive_adapter_test.go
  pkg/apis/sources/v1alpha1/gitlabsource_lifecyle.go
  pkg/apis/sources/v1alpha1/gitlabsource_lifecyle_test.go
  pkg/apis/sources/v1alpha1/gitlabsource_types.go
  pkg/reconciler/source/gitlabsource.go
  pkg/reconciler/source/webhook_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#29 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#31 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#32 [release-0.18] Bump xanzy/go-gitlab and go-playground/webhooks deps
  go.mod
  go.sum
  pkg/adapter/receive_adapter.go
  pkg/adapter/receive_adapter_test.go
  vendor/github.com/xanzy/go-gitlab/.travis.yml
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/client_options.go
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/deploy_keys.go
  vendor/github.com/xanzy/go-gitlab/epics.go
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/freeze_periods.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_boards.go
  vendor/github.com/xanzy/go-gitlab/group_clusters.go
  vendor/github.com/xanzy/go-gitlab/group_labels.go
  vendor/github.com/xanzy/go-gitlab/group_members.go
  vendor/github.com/xanzy/go-gitlab/group_milestones.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/instance_clusters.go
  vendor/github.com/xanzy/go-gitlab/instance_variables.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/issues_statistics.go
  vendor/github.com/xanzy/go-gitlab/jobs.go
  vendor/github.com/xanzy/go-gitlab/labels.go
  vendor/github.com/xanzy/go-gitlab/license.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/milestones.go
  vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/project_members.go
  vendor/github.com/xanzy/go-gitlab/project_mirror.go
  vendor/github.com/xanzy/go-gitlab/project_snippets.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/registry.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/tags.go
  vendor/github.com/xanzy/go-gitlab/types.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/gopkg.in/go-playground/webhooks.v5/gitlab/gitlab.go
  vendor/gopkg.in/go-playground/webhooks.v5/gitlab/payload.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#34 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#35 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#33 [release-0.18] Set proper type and source attributes on emitted CloudEvents
  config/300-gitlabsource.yaml
  config/500-controller.yaml
  go.mod
  pkg/adapter/receive_adapter.go
  pkg/adapter/receive_adapter_test.go
  pkg/apis/sources/v1alpha1/gitlabsource_lifecyle.go
  pkg/apis/sources/v1alpha1/gitlabsource_lifecyle_test.go
  pkg/apis/sources/v1alpha1/gitlabsource_types.go
  pkg/reconciler/source/gitlabsource.go
  pkg/reconciler/source/webhook_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#30 Set POD_NAME env var for logger injection
  config/500-controller.yaml
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#36 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#38 Fix a few more occurrences of divisive language
  config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#39 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#40 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#41 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#42 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#44 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#45 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#46 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#47 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#48 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#49 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#50 Get webhook name from common pkg
  cmd/webhook/main.go
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#51 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/serving/pkg/client/injection/client/client.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#52 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#53 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#54 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
