Repository knative-extensions/eventing-gitlab, pull requests merged in 2021-04, with the labels that each got.

#136 Fix deletion of id field from gitlabsource
  config/300-gitlabsource.yaml
  pkg/apis/sources/v1alpha1/gitlabsource_types.go
Labels: approved, cla: yes, lgtm, size/XS

#138 Remove lease name pinning in ClusterRole
  config/201-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#146 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
