Repository knative-extensions/eventing-gitlab, pull requests merged in 2021-08, with the labels that each got.

#184 bump go to 1.16
  go.mod
Labels: cla: yes, size/XS, approved, lgtm

#183 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/modules.txt
Labels: cla: yes, size/M, approved, lgtm

#185 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/XS, approved, lgtm

#186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/XS, approved, lgtm

#187 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, approved, lgtm

#188 [main] Format Go code
  hack/tools.go
Labels: cla: yes, size/XS, approved, lgtm

#190 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, approved, lgtm

#189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/bindings/v1alpha1/gitlabbinding/filtered/gitlabbinding.go
  pkg/client/injection/informers/bindings/v1alpha1/gitlabbinding/gitlabbinding.go
  pkg/client/injection/informers/sources/v1alpha1/gitlabsource/filtered/gitlabsource.go
  pkg/client/injection/informers/sources/v1alpha1/gitlabsource/gitlabsource.go
  pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/gitlabsource/reconciler.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/client/injection/client/client.go
  vendor/knative.dev/serving/pkg/client/injection/informers/serving/v1/service/service.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, approved, lgtm

#191 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, approved, lgtm

#195 Use `controller.Impl` tracker and cleanups
  pkg/reconciler/binding/controller.go
  pkg/reconciler/source/controller.go
Labels: cla: yes, size/S, kind/cleanup, approved, lgtm
