Repository knative-extensions/eventing-gitlab, pull requests merged in 2023-11, with the labels that each got.

#417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#418 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#420 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: size/S, approved, lgtm

#424 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, approved, lgtm

#423 Add timeouts on receive adapter
  pkg/adapter/receive_adapter.go
Labels: size/XS, approved, lgtm

#426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review

#425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: size/M, approved, lgtm
