Repository knative-extensions/eventing-gitlab, pull requests merged in 2024-01, with the labels that each got.

#432 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#434 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#435 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#436 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#437 Remove unneeded go toolchain directive
  go.mod
Labels: size/XS, approved, lgtm

#439 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, approved, lgtm

#440 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#442 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: size/M, approved, lgtm
