Repository knative-extensions/eventing-gitlab, pull requests merged in 2024-04, with the labels that each got.

#473 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#474 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#475 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#476 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#477 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#478 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#480 Pass application context to adapter setup
  cmd/receive_adapter/main.go
Labels: size/XS, approved, lgtm

#483 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#484 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#486 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, approved, lgtm

#488 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
